//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int Id { get; set; }
        [Required (ErrorMessage="Please enter valid from-date")]
        [Display(Name = "Fromdate")]
       
         public Nullable<System.DateTime> fromDate { get; set; }
        [Required(ErrorMessage = "Please enter valid to-date")]
        [Display(Name = "Todate")]
     
        public Nullable<System.DateTime> toDate { get; set; }

        [Required]
        [Display(Name = "Room count")]
        //[Range(1, 5, ErrorMessage = "you can book only 1-5 rooms via the web system  ")]

        public Nullable<int> roomCount { get; set; }
        [Required]
        [Display(Name = "Visitor count")]
        [Range(1, 30, ErrorMessage = "Please enter 1-30 visitors.(If you need to book for more visitors, please contract a booking agent)")]

        public Nullable<int> visitorCount { get; set; }
        [Display(Name = "Total Price")]
        public Nullable<int> totalPrice { get; set; }
        public string userId { get; set; }
       
        public Nullable<int> branchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Branch cdate { get; set; }
        public virtual int reviewsts { get; set; }

        
    }
}
