//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Bookings = new HashSet<Booking>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(100,MinimumLength =2,ErrorMessage ="The hotel name length needs to be less than 10 characters ")]
        [Display(Name = "Name")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Address")]
        [StringLength(150,MinimumLength =3,ErrorMessage ="Address length needs to be less than 150")]
        public string address { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        [Required]
        [Display(Name="Room Price")]
        [Range(0,int.MaxValue,ErrorMessage ="Please enter a valid number for room price")]
        public Nullable<int> roomPrice { get; set; }
        [Required]
        [Display(Name="Available Rooms")]
        [Range(0,int.MaxValue,ErrorMessage ="PLease enter valid number for available rooms")]
        public Nullable<int> availableRooms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
