//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Discount
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Discount Value")]
        [Range(0, 100, ErrorMessage = "Please enter 0-100 value")]

        public Nullable<int> value { get; set; }

        [Required(ErrorMessage = "Please enter valid From-date")]
        [Display(Name = "FromDate")]

        public Nullable<System.DateTime> fromdate { get; set; }
        [Required(ErrorMessage = "Please enter valid To-date")]
        [Display(Name = "ToDate")]

        public Nullable<System.DateTime> todate { get; set; }
    }
}
